version: '3'
services:
  web:
    image: trzl/bass-web
    container_name: bass-web
    restart: unless-stopped
    expose:
      - "80"
      - "443"
    environment:
      VIRTUAL_HOST: bass.tbrownkcdev.com
      LETSENCRYPT_HOST: bass.tbrownkcdev.com
      LETSENCRYPT_EMAIL: brownty47@gmail.com
networks:
  default:
    external:
      name: webproxy
